### ISSUE TITLE
Build fails on MacOS 10.13.6 with clang error: use of undeclared identifier 'IUCLC'

### ISSUE THREAD

**Issue by martin-c** [euantorano/serial.nim#39]
Thanks for this excellent Nim package!
Unfortunately the latest version v1.1.3 (and master 17fbff9) fails to build on MacOS 10.13.6. Here's the full clang error:
```
/Users/martin/.cache/nim/serial_d/@mserial@sserialport.nim.c:1136:111: error: use of undeclared identifier 'IUCLC'
                settings.c_iflag = (NU32)(settings.c_iflag & (NU32)((NU32) ~((NU32)((NU32)((NU32)(INLCR | IGNCR) | ICRNL) | IUCLC))));
```
I read up on the meaning of `IUCLC` here: http://man7.org/linux/man-pages/man3/termios.3.html and noted that the man page states that 

> IUCLC  (not in POSIX) Map uppercase characters to lowercase on input.'

So should we remove it from the `serialport_posix.nim` file?
Changing line 599 to remove `IUCLC` fixes the error.

**Comment by euantorano** [comment]
Yes, that seems like a good solution to me, thanks.
